Dbg dump info
CoolITSystemsInc/cdu-board-bootloader pull request #7
Opened 2024-08-28 22:56 UTC by Jordanwangxy

1. Revised dgb_dump() function and callers
2. Revised github yml file to build 2 iar projects in one action file.

2024-08-30 17:27 UTC, JCordara-CoolIT approved these changes

2024-08-30 17:52 UTC, PeteHeckel requested changes
Minor notes, looks good mainly

2024-08-30 17:52 UTC, PeteHeckel commented on User/Inc/main.h
> +extern const uint8_t dbg_info_j2app[];
Why are we defining these as global variables? Why can't they just be strings local to where they're called?

2024-08-30 17:52 UTC, PeteHeckel commented on User/Src/main.c
> +  HAL_UART_Transmit(&huart2, pData, Size, 20);
Could you specify the magic number with a macro indicating what it is / units?

2024-08-30 17:52 UTC, PeteHeckel commented on User/Src/main.c
> +static bool not_enter_bootloader_mode_reset(bool adapter_app)
Could you update this comment to be representative of the function? Also maybe re-think the name of the function; it's functionality isn't super clear to me based off the name.

2024-08-30 17:52 UTC, PeteHeckel commented on User/Src/main.c
> +  if ((__HAL_RCC_GET_FLAG(RCC_FLAG_LPWRRST)) ||
Minor nit but this could just be a return statement instead of a conditional

2024-08-30 20:51 UTC, JCordara-CoolIT requested changes
Just a few more requests to finalize the changes

2024-08-30 20:51 UTC, JCordara-CoolIT commented on User/Src/main.c
> +  HAL_UART_Transmit(&huart2, pData, sizeof(pData), 20);
Does sizeof work here? I would've expected strlen to be used.

I agree with Peter here as well that the 20 should be replaced by a macro. (e.g. DBG_UART_TIMEOUT_MS)

2024-08-30 20:51 UTC, JCordara-CoolIT commented on User/Src/main.c
>    return true;
I might suggest re-writing this function as the following:
```c
static bool is_app_sw_reset(void)
{
  return !(
    (__HAL_RCC_GET_FLAG(RCC_FLAG_LPWRRST)) ||
    (__HAL_RCC_GET_FLAG(RCC_FLAG_WWDGRST)) ||
    (__HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST)) ||
    (__HAL_RCC_GET_FLAG(RCC_FLAG_PORRST)) ||
#ifdef RS485_ADAPTER
    (__HAL_RCC_GET_FLAG(RCC_FLAG_OBLRST)) ||
#else
    (__HAL_RCC_GET_FLAG(RCC_FLAG_BORRST))
#endif
  );
}
```

2024-09-05 16:11 UTC, PeteHeckel approved these changes

2024-09-05 18:37 UTC, ChristieNgan approved these changes

2024-09-06 14:43 UTC, merged